
import { Inter } from 'next/font/google'
import ClientOnly from './components/ClientOnly'
import Navbar from './components/navbar/navbar'
import './globals.css'
import SearchModal from './modals/SearchModal'

export const dynamic = 'force-dynamic'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>


        <ClientOnly><Navbar /><SearchModal /></ClientOnly>
        <div className='pb-20 pt-28'>
          {children}
        </div>





      </body>
    </html>
  )
}
